=== sGooze/KioskWatcher/ext-settings.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://abitlist.rea.ru/ext-settings.schema.json",
    "title": "Схема параметров дополнения",
    "description": "Схема параметров дополнения, доступных для изменения пользователем на странице настройки",
    "type": "array",
    "items": {
        "type": "object",
        "title": "Параметр",
        "description": "Настраиваемый пользователем параметр",
        "properties": {
            "id":{
                "type": "string",
                "title": "Идентификатор",
                "description": "Уникальный идентификатор параметра, используемый в коде для получения его значения",
                "pattern": "^[a-zA-Z]{1}\\w*$"
            },
            "title":{
                "type": "string",
                "title": "Описание",
                "description": "Краткое описание параметра, отображаемое на странице настроек"
            },
            "subtitle":{
                "type": "string",
                "title": "Комментарий",
                "description": "Дополнительная информация, поясняющая назначение параметра"
            },
            "type":{
                "type": "string",
                "title": "Тип данных",
                "description": "Тип данных параметра. Определяет, какой контрол будет использоваться для его изменения",
                "enum": ["boolean", "number", "string", "url"]
            },
            "defaultValue":{
                "type":["boolean", "number", "string"],
                "title": "Значение по умолчанию",
                "description": "Значение параметра по умолчанию"
            }
        },
        "required": [
            "id",
            "title",
            "type",
            "defaultValue"
        ],
        "additionalProperties": false
    },
    "uniqueItems": true
}

=== sGooze/KioskWatcher/ext-settings.json
[
    {
        "id": "kioskHome",
        "type": "url",
        "title": "Домашняя страница для режима киоска",
        "defaultValue": "https://abitlist.rea.ru?kiosk=true"
    },
    {
        "id": "restrictRedirect",
        "type": "boolean",
        "title": "Включить перенаправление страниц",
        "subtitle": "Перенаправляет все запросы, ведущие за пределы домена домашней страницы, на главную странцу киоска",
        "defaultValue": true
    },
    {
        "id": "autoLogout",
        "type": "boolean",
        "title": "Автоматический выход из ЛКС",
        "subtitle": "НЕ ИСПОЛЬЗУЕТСЯ НЕ ИСПОЛЬЗУЕТСЯ НЕ ИСПОЛЬЗУЕТСЯ НЕ ИСПОЛЬЗУЕТСЯ",
        "defaultValue": false
    },
    {
        "id": "autoLogoutTime",
        "type": "number",
        "title": "Тайм-аут автоматического выхода из ЛКС, сек.",
        "defaultValue": 60
    },
    {
        "id": "killTabs",
        "type": "boolean",
        "title": "Закрывать все новые вкладки и окна",
        "subtitle": "Не распространяется на about:newtab и приватные вкладки",
        "defaultValue": true
    },
    {
        "id": "allowContext",
        "type": "boolean",
        "title": "Разрешить открытие контекстного меню",
        "subtitle": "Контекстное меню всегда можно открыть с помощью Shift+ПКМ или Shift+≣Menu",
        "defaultValue": false
    },
    {
        "id": "fullscreenOnStartup",
        "type": "boolean",
        "title": "Переключить браузер в режим \"На весь экран\" сразу после запуска",
        "defaultValue": true
    },
    {
        "id": "kioskAlwaysInFocus",
        "type": "boolean",
        "title": "Всегда держать окно киоска в фокусе",
        "subtitle": "При переключении фокуса на другое окно фокус будет автоматически возвращён обратно",
        "defaultValue": true
    }
]
